[defaults]
# WalkFSM5
walkFSM5IcThresholdSpinBox = 225
walkFSM5ToThresholdSpinBox = 200
walkFSM5DeadZoneTimeDoubleSpinBox = 0.150

walkFSM5ExtLimitSpinBox = -15
walkFSM5FlexLimitSpinBox = 90

walkFSM5StanceRampRateSpinBox = 80
walkFSM5SwingRampRateSpinBox = 80

walkFSM5TimeoutToWaitingDoubleSpinBox = 4.000

walkFSM5EarlyToMidStanceThresholdSpinBox = -5
walkFSM5MidToLateStanceThresholdSpinBox = 5
walkFSM5EarlyToLateSwingThresholdSpinBox = -10

# Proportional
proportionalMinAngleLimitSpinBox = 0
proportionalMaxAngleLimitSpinBox = 90
proportionalMinTorqueDoubleSpinBox = -10
proportionalMaxTorqueDoubleSpinBox = 0

# Standing
standingModeComboBox = 0
standingTorqueDoubleSpinBox = -3.5
standingRampRateSpinBox = 5
standingTurnOffThresholdSpinBox = 0
standingTurnOnThresholdSpinBox = 15

[limits]
    # WalkFSM5
        [limits.walkFSM5IcThresholdSpinBox]
        minimum = 0
        maximum = 9500

        [limits.walkFSM5ToThresholdSpinBox]
        minimum = 0
        maximum = 9500

        [limits.walkFSM5DeadZoneTimeDoubleSpinBox]
        minimum = 0

        [limits.walkFSM5EarlyToMidStanceThresholdSpinBox]
        minimum = -200
        maximum = 200

        [limits.walkFSM5MidToLateStanceThresholdSpinBox]
        minimum = -200
        maximum = 200

        [limits.walkFSM5EarlyToLateSwingThresholdSpinBox]
        minimum = -200
        maximum = 200

        [limits.walkFSM5ExtLimitSpinBox]
        minimum = -30
        maximum = 30

        [limits.walkFSM5FlexLimitSpinBox]
        minimum = 60
        maximum = 120

        [limits.walkFSM5StanceRampRateSpinBox]
        minimum = 40
        maximum = 80

        [limits.walkFSM5SwingRampRateSpinBox]
        minimum = 40
        maximum = 80

        [limits.walkFSM5EarlyStanceTorqueDoubleSpinBox]
        minimum = -13
        maximum = 13
        stepSize = 0.25

        [limits.walkFSM5MidStanceTorqueDoubleSpinBox]
        minimum = -13
        maximum = 13
        stepSize = 0.25

        [limits.walkFSM5LateStanceTorqueDoubleSpinBox]
        minimum = -13
        maximum = 13
        stepSize = 0.25

        [limits.walkFSM5EarlySwingTorqueDoubleSpinBox]
        minimum = -13
        maximum = 13
        stepSize = 0.25

        [limits.walkFSM5LateSwingTorqueDoubleSpinBox]
        minimum = -13
        maximum = 13
        stepSize = 0.25

        [limits.walkFSM5TimeoutToWaitingDoubleSpinBox]
        minimum = 0

    # Proportional
        [limits.proportionalMinAngleLimitSpinBox]
        minimum = 0
        maximum = 90

        [limits.proportionalMaxAngleLimitSpinBox]
        minimum = 0
        maximum = 90

        [limits.proportionalMinTorqueDoubleSpinBox]
        minimum = -13
        maximum = 13
        stepSize = 0.25

        [limits.proportionalMaxTorqueDoubleSpinBox]
        minimum = -13
        maximum = 13
        stepSize = 0.25

    # Standing
        [limits.standingTorqueDoubleSpinBox]
        minimum = -13
        maximum = 13
        stepSize = 0.25

        [limits.standingRampRateSpinBox]
        minimum = 1
        maximum = 80

[leg]
    [leg.BPID-1887]
    isExtensionPositive = true
    legSide = "left"

    [leg.BPID-1884]
    isExtensionPositive = true
    legSide = "right"

    [leg.BPID-1865]
    isExtensionPositive = false
    legSide = "left"

    [leg.BPID-1864]
    isExtensionPositive = true
    legSide = "right"

[settings]
hasTrigger = true
hostAddress = "raspberrypi"
hostPort = 8080

commandTopic = "remotecommands/command"
remoteHostTopic = "remotecommands/return/$hostname"
triggerTopicName = "trigger"
dataTopicName = "datatypes"

